package:
  name: r-r.matlab
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "3.2.0"

source:
  fn: R.matlab_3.2.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/R.matlab_3.2.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/R.matlab/R.matlab_3.2.0.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: Matrix, SparseM
requirements:
  build:
    - r >=2.5.0
    - r-r.methodss3 >=1.7.0
    - r-r.oo >=1.18.0
    - r-r.utils >=1.34.0

  run:
    - r >=2.5.0
    - r-r.methodss3 >=1.7.0
    - r-r.oo >=1.18.0
    - r-r.utils >=1.34.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('R.matlab')" # [not win]
    - "\"%R%\" -e \"library('R.matlab')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://github.com/HenrikBengtsson/R.matlab'

  license: LGPL (>= 2.1)
  summary: !!python/unicode 'Methods readMat() and writeMat() for reading and writing MAT files.  For
    user with MATLAB v6 or newer installed (either locally or on a remote host), the
    package also provides methods for controlling MATLAB (trademark) via R and sending
    and retrieving data between R and MATLAB.'


# The original CRAN metadata for this package was:

# Package: R.matlab
# Version: 3.2.0
# Depends: R (>= 2.5.0)
# Imports: utils, R.methodsS3 (>= 1.7.0), R.oo (>= 1.18.0), R.utils (>= 1.34.0)
# Suggests: Matrix, SparseM
# Date: 2015-02-24
# Title: Read and Write MAT Files and Call MATLAB from Within R
# Authors@R: c( person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email="henrikb@braju.com"), person("Andy", "Jacobson", role="ctb", comment="Internal MAT v4 reader"), person("Jason", "Riedy", role="ctb", email="ejr@cs.berkeley.edu", comment="Support for reading compressed files (via 'Rcompression'), sparse matrices and UTF-encoded strings."))
# Author: Henrik Bengtsson [aut, cre, cph], Andy Jacobson [ctb] (Internal MAT v4 reader), Jason Riedy [ctb] (Support for reading compressed files (via 'Rcompression'), sparse matrices and UTF-encoded strings.)
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Description: Methods readMat() and writeMat() for reading and writing MAT files.  For user with MATLAB v6 or newer installed (either locally or on a remote host), the package also provides methods for controlling MATLAB (trademark) via R and sending and retrieving data between R and MATLAB.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# ByteCompile: TRUE
# URL: https://github.com/HenrikBengtsson/R.matlab
# BugReports: https://github.com/HenrikBengtsson/R.matlab/issues
# NeedsCompilation: no
# Packaged: 2015-02-25 01:14:06 UTC; hb
# Repository: CRAN
# Date/Publication: 2015-02-25 08:12:28

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml