package:
  name: keytree
  version: !!str 0.2.1

source:
  fn: keytree-0.2.1.tar.gz
  url: https://pypi.python.org/packages/source/k/keytree/keytree-0.2.1.tar.gz
  md5: 2b75f82071a4dfe6fafc959180947995
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - keytree = keytree:main
    #
    # Would create an entry point called keytree that calls keytree.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - keytree
    - keytree.tests

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://atlantides.org/svn/pleiades/pleiades.keytree
  license: BSD License
  summary: 'KML utilities for the ElementTree API'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
