package:
    name: ctags
    version: 5.8

build:
    script: ./configure --prefix=$PREFIX && make && make install

source:
    url: http://prdownloads.sourceforge.net/ctags/ctags-5.8.tar.gz
    sha256: 0e44b45dcabe969e0bbbb11e30c246f81abe5d32012db37395eb57d66e9e99c7

test:
    commands:
        - ctags --version

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
