package:
  name: hsfuap

source:
  git_url: https://github.com/dougalsutherland/hsfuap.git

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

  entry_points:
    - hsfuap-nystroem = hsfuap.kernels.nystroem:main
    - hsfuap-sdm-gather = hsfuap.sdm.gather_results:main
    - hsfuap-sdm-kernelize = hsfuap.sdm.make_kernels:main

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - humanize
    - gcc

  run:
    - python
    - numpy
    - scipy
    - humanize
    - pandas
    - scikit-learn
    - six
    - libgcc

test:
  imports:
    - hsfuap.kde._bandwidth

about:
  home: https://github.com/dougalsutherland/hsfuap
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
