package:
  name: r-kernlab
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.9_25"

source:
  fn: kernlab_0.9-25.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/kernlab_0.9-25.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/kernlab/kernlab_0.9-25.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('kernlab')" # [not win]
    - "\"%R%\" -e \"library('kernlab')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-2
  summary: !!python/unicode 'Kernel-based machine learning methods for classification, regression,
    clustering, novelty detection, quantile regression and dimensionality reduction.  Among
    other methods kernlab includes Support Vector Machines, Spectral Clustering, Kernel
    PCA, Gaussian Processes and a QP solver.'


# The original CRAN metadata for this package was:

# Package: kernlab
# Version: 0.9-20
# Title: Kernel-based Machine Learning Lab
# Authors@R: c(person("Alexandros", "Karatzoglou", role = c("aut", "cre"), email = "alexis@ci.tuwien.ac.at"), person("Alex", "Smola", role = "aut"), person("Kurt", "Hornik", role = "aut"))
# Description: Kernel-based machine learning methods for classification, regression, clustering, novelty detection, quantile regression and dimensionality reduction.  Among other methods kernlab includes Support Vector Machines, Spectral Clustering, Kernel PCA, Gaussian Processes and a QP solver.
# Depends: R (>= 2.10), methods
# LazyLoad: Yes
# License: GPL-2
# Packaged: 2015-01-10 07:59:39 UTC; hornik
# Author: Alexandros Karatzoglou [aut, cre], Alex Smola [aut], Kurt Hornik [aut]
# Maintainer: Alexandros Karatzoglou <alexis@ci.tuwien.ac.at>
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2015-01-10 09:33:22

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
