package:
  name: leveldb
  version: "0.193"

source:
  fn: leveldb-0.193.tar.gz
  url: https://pypi.python.org/packages/source/l/leveldb/leveldb-0.193.tar.gz
  md5: 2952434f2a0ce10c44f58542cc561589
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - leveldb = leveldb:main
    #
    # Would create an entry point called leveldb that calls leveldb.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - leveldb

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://code.google.com/p/py-leveldb/
  license: BSD License
  summary: 'Python bindings for leveldb database library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
