package:
  name: pyuv
  version: !!str 0.10.11

source:
  fn: pyuv-0.10.11.tar.gz
  url: https://pypi.python.org/packages/source/p/pyuv/pyuv-0.10.11.tar.gz
  md5: 2a6e535b8068f0cd71876523e4bc23ad
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyuv = pyuv:main
    #
    # Would create an entry point called pyuv that calls pyuv.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools

test:
  # Python imports
  imports:
    - pyuv

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/saghul/pyuv
  license:  MIT License
  summary: 'Python interface for libuv'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
