package:
  name: async
  version: !!str 0.6.1

source:
  fn: async-0.6.1.tar.gz
  url: https://pypi.python.org/packages/source/a/async/async-0.6.1.tar.gz
  md5: 6f0e2ced1fe85f8410b9bde11be08587
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - async = async:main
    #
    # Would create an entry point called async that calls async.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - async
    - async.mod
    - async.test
    - async.test.mod

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/gitpython-developers/async
  license: New BSD License
  summary: 'Async Framework'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
