package:
  name: progressbar
  version: 0.2.3

source:
  git_url: https://github.com/dougalsutherland/python-progressbar.git
  git_tag: 6381cd0a2770ae536756d3084aaa6069c347ba20

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - progressbar

about:
  home: https://github.com/dougalsutherland/python-progressbar
  license: BSD License
