package:
  name: progressbar
  version: 0.2.3

source:
  git_url: https://github.com/fnoble/python-progressbar.git

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  imports:
    - progressbar

about:
  home: https://github.com/dougalsutherland/vlfeat-ctypes
  license: BSD License
