package:
  name: gitdb
  version: !!str 0.6.0

source:
  fn: gitdb-0.6.0.tar.gz
  url: https://pypi.python.org/packages/source/g/gitdb/gitdb-0.6.0.tar.gz
  md5: fbd7d617e208e8d8029beeb09a18f845
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - gitdb = gitdb:main
    #
    # Would create an entry point called gitdb that calls gitdb.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - smmap >=0.8.3

  run:
    - python
    - smmap >=0.8.3

test:
  # Python imports
  imports:
    - gitdb
    - gitdb.db

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD License
  summary: 'Git Object Database'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
