package:
  name: cvxopt
  version: 1.1.6

source:
  fn: cvxopt-1.1.6.tar.gz
  url: https://pypi.python.org/packages/source/c/cvxopt/cvxopt-1.1.6.tar.gz
  md5: 190ff21beba1c27eb6a9673cfc2ba1a3

  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - cvxopt

about:
  home: http://cvxopt.org
  license: GNU GPL version 3
  summary: 'Convex optimization package'
