package:
  name: emcee
  version: !!str 2.1.0

source:
  fn: emcee-2.1.0.tar.gz
  url: https://pypi.python.org/packages/source/e/emcee/emcee-2.1.0.tar.gz
  md5: c6b6fad05c824d40671d4a4fc58dfff7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - emcee = emcee:main
    #
    # Would create an entry point called emcee that calls emcee.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - emcee

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://dan.iel.fm/emcee/
  license:  MIT License
  summary: 'Kick ass affine-invariant ensemble MCMC sampling'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
