package:
    name: pyflann
    version: 1.8.5dev

build:
    number: 9

source:
    # conda-build doesn't support subdirectories of git repos
    git_url: git@github.com:mariusmuja/flann.git
    git_tag: 31bcbefca205fb9febcaa6823139fd3525f21ed3

requirements:
    build:
        - python
        - flann
    run:
        - python
        - numpy
        - flann

test:
  imports:
    - pyflann

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
