package:
    name: pyflann
    version: 1.9.1

build:
    number: 0

source:
    # conda-build doesn't support subdirectories of git repos
    git_url: https://github.com/mariusmuja/flann.git
    git_tag: 1.9.1

requirements:
    build:
        - python
        - flann
    run:
        - python
        - numpy
        - flann

test:
  imports:
    - pyflann

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
