package:
    name: pyflann
    version: 1.8.5dev

build:
    number: 0

source:
    # conda-build doesn't support subdirectories of git repos
    git_url: git@github.com:mariusmuja/flann.git
    git_tag: 894c1b975e299d15487a6a498862c6b1df39de28

requirements:
    build:
        - python
        - flann
    run:
        - python
        - numpy
        - flann

test:
  imports:
    - pyflann

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License