package:
    name: pyflann
    version: 1.8.5dev

build:
    number: 1

source:
    # conda-build doesn't support subdirectories of git repos
    git_url: https://github.com/mariusmuja/flann.git
    git_tag: 04b4a56533faf8c8228d011d05ba376038364b49

    patches:
        - find_lib.patch
        - setup_py.patch

requirements:
    build:
        - python
        - flann
    run:
        - python
        - numpy
        - flann

test:
  imports:
    - pyflann

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
