package:
    name: pyflann
    version: 1.9.1

build:
    number: 1

source:
    url: https://github.com/mariusmuja/flann/archive/1.9.1.tar.gz
    sha256: b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3

requirements:
    build:
        - python
        - flann
    run:
        - python
        - numpy
        - flann

test:
  imports:
    - pyflann

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
