package:
  name: skl-groups
  version: 0.1.5

source:
  git_url: https://github.com/dougalsutherland/skl-groups.git
  git_tag: 0.1.5

build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - skl-groups = skl-groups:main
    #
    # Would create an entry point called skl-groups that calls skl-groups.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - numpy
    - scipy
    - setuptools
    - scikit-learn
    - cyflann
    - pip
    - cython
    - versiontools
    - gitpython [not py3k]
    - gcc [osx]

  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - cyflann
    - libgcc [osx]

test:
  imports:
    - skl_groups
    - skl_groups.divergences
    - skl_groups.summaries
    - skl_groups.tests

  requires:
    - nose
    - testfixtures

  commands:
    - nosetests --exe skl_groups
  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.


about:
  home: https://github.com/dougalsutherland/skl-groups
  license: BSD License
  summary: 'Addon to scikit-learn for handling set-based data.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
