package:
  name: skl-groups
  version: 0.1.1

source:
  fn: skl-groups-0.1.1.tar.gz
  url: https://pypi.python.org/packages/source/s/skl-groups/skl-groups-0.1.1.tar.gz
  md5: 8153527a0eed4e690fba61c02db4bf5a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - skl-groups = skl-groups:main
    #
    # Would create an entry point called skl-groups that calls skl-groups.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - scipy
    - setuptools
    - scikit-learn >=0.13
    - cyflann
    - pip
    - cython

  run:
    - python
    - numpy
    - scipy
    - scikit-learn >=0.13
    - cyflann

test:
  # Python imports
  imports:
    - skl_groups
    - skl_groups.divergences
    - skl_groups.summaries
    - skl_groups.tests

  commands:
    - nosetests --exe skl_groups


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    # Put any additional test requirements here.  For example
    - nose
    - testfixtures

about:
  home: https://github.com/dougalsutherland/skl-groups
  license: BSD License
  summary: 'Addon to scikit-learn for handling set-based data.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
