package:
  name: r-huge
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.2.6"

source:
  fn: huge_1.2.6.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/huge_1.2.6.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/huge/huge_1.2.6.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r >=3.0.0
    - r-mass # [not win]
    - r-matrix # [not win]
    - r-igraph
    - r-lattice # [not win]

  run:
    - r >=3.0.0
    - r-mass # [not win]
    - r-matrix # [not win]
    - r-igraph
    - r-lattice # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('huge')" # [not win]
    - "\"%R%\" -e \"library('huge')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-2
  summary: !!python/unicode 'The package "huge" provides a general framework for high-dimensional
    undirected graph estimation. It integrates data preprocessing, neighborhood screening,
    graph estimation, and model selection techniques into a pipeline. In preprocessing
    stage, the nonparanormal(npn) transformation is applied to help relax the normality
    assumption. In the graph estimation stage, the graph structure is estimated by Meinshausen-Buhlmann
    graph estimation or the graphical lasso, and both methods can be further accelerated
    by the lossy screening rule preselecting the neighborhood of each variable by correlation
    thresholding. We target on high-dimensional data analysis usually d >> n, and the
    computation is memory-optimized using the sparse matrix output. We also provide
    a computationally efficient approach, correlation thresholding graph estimation.
    Three regularization/thresholding parameter selection methods are included in this
    package: (1)stability approach for regularization selection (2) rotation information
    criterion (3) extended Bayesian information criterion which is only available for
    the graphical lasso.'


# The original CRAN metadata for this package was:

# Package: huge
# Type: Package
# Title: High-dimensional Undirected Graph Estimation
# Version: 1.2.6
# Date: 2014-02-16
# Author: Tuo Zhao, Han Liu, Kathryn Roeder, John Lafferty, Larry Wasserman
# Maintainer: Tuo Zhao <tzhao5@jhu.edu>
# Depends: R (>= 3.0.0), Matrix, lattice, igraph, MASS
# Description: The package "huge" provides a general framework for high-dimensional undirected graph estimation. It integrates data preprocessing, neighborhood screening, graph estimation, and model selection techniques into a pipeline. In preprocessing stage, the nonparanormal(npn) transformation is applied to help relax the normality assumption. In the graph estimation stage, the graph structure is estimated by Meinshausen-Buhlmann graph estimation or the graphical lasso, and both methods can be further accelerated by the lossy screening rule preselecting the neighborhood of each variable by correlation thresholding. We target on high-dimensional data analysis usually d >> n, and the computation is memory-optimized using the sparse matrix output. We also provide a computationally efficient approach, correlation thresholding graph estimation. Three regularization/thresholding parameter selection methods are included in this package: (1)stability approach for regularization selection (2) rotation information criterion (3) extended Bayesian information criterion which is only available for the graphical lasso.
# License: GPL-2
# Repository: CRAN
# Date/Publication: 2014-02-28 07:00:50
# Packaged: 2014-02-28 05:26:52 UTC; tourzhao
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml