package:
  name: scs
  version: !!str 1.0.5

source:
  fn: scs-1.0.5.tar.gz
  url: https://pypi.python.org/packages/source/s/scs/scs-1.0.5.tar.gz
  md5: c0d5c0d2b05a23346cd019e7fb8e4aff
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scs = scs:main
    #
    # Would create an entry point called scs that calls scs.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy

test:
  # Python imports
  imports:
    - scs

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/cvxgrp/scs
  license: GPLv3
  summary: 'scs: splittling cone solver'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
