package:
  name: rtree
  version: !!str 0.8.2

source:
  fn: Rtree-0.8.2.tar.gz
  url: https://pypi.python.org/packages/16/68/c79bed9d7fa4479b37d7a898b71d1e89099a8c15fac5c5d94328cb0a1ac9/Rtree-0.8.2.tar.gz
  md5: 4ba7276cbdb4c51b373068004ae864d3

build:
  preserve_egg_dir: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - libspatialindex

  run:
    - python
    - setuptools
    - libspatialindex

test:
  imports:
    - rtree

about:
  home: http://toblerity.github.com/rtree/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'R-Tree spatial index for Python GIS'
