package:
  name: pystan
  version: 2.0.1.0

source:
  fn: pystan-2.0.1.0.tar.gz
  url: https://pypi.python.org/packages/source/p/pystan/pystan-2.0.1.0.tar.gz
  md5: f33e08c1ad2b301a994701299d1fa112

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy
    - cython

  run:
    - python
    - numpy
    - cython

test:
  imports:
    - pystan

  requires:
    - nose

  commands:
    - nosetests --exe pystan.tests.test_basic

about:
  home: https://github.com/stan-dev/pystan
  license: GNU General Public License
