package:
  name: ecos
  version: 1.0.4

source:
  fn: ecos-1.0.4.tar.gz
  url: https://pypi.python.org/packages/source/e/ecos/ecos-1.0.4.tar.gz
  md5: fba0c5cf732866f8e0081bd12be4878f

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy
    - scipy

test:
  imports:
    - ecos

about:
  home: http://github.com/ifa-ethz/ecos
  license: GPLv3
  summary: 'This is the Python package for ECOS: Embedded Cone Solver. See Github page for more information.'
