package:
  name: py-sdm
  version: 0.1.0dev

source:
  git_url: https://github.com/dougalsutherland/py-sdm.git
  git_tag: conda-0.1.0dev_8

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 8

  entry_points:
    - extract_image_features = sdm.extract_image_features:main
    - proc_image_features = sdm.proc_image_features:main
    - estimate_divs = sdm.np_divs:main
    - sdm = sdm.sdm:main

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - cython
    - flann
    - cyflann
    - scikit-learn
    - scikit-image
    - vlfeat-ctypes
    - h5py
    - nose
    - progressbar
    # TODO: can maybe tell setup.py to ignore dependencies?

  run:
    - python
    - numpy
    - scipy
    - flann
    - cyflann
    - scikit-learn
    - scikit-image
    - vlfeat-ctypes
    - h5py
    - progressbar

test:
  imports:
    - sdm

  commands:
      - nosetests --exe sdm.tests.test_divs

  requires:
    - nose

about:
  home: https://github.com/dougalsutherland/py-sdm
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
