package:
  name: bottleneck
  version: 0.8.0

source:
  fn: Bottleneck-0.8.0.tar.gz
  url: https://pypi.python.org/packages/source/B/Bottleneck/Bottleneck-0.8.0.tar.gz
  md5: 1a363fa35ce521eebb838e1bd6520e24

# build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - numpy  # requires 1.8, but conda doesn't let you say that

  run:
    - python
    - numpy

test:
  # run_test.py calls the bottleneck test suite
  requires:
    - nose

about:
  home: http://berkeleyanalytics.com/bottleneck
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
