package:
  name: cyflann
  version: 0.1.19

source:
  fn: cyflann-0.1.19.tar.gz
  url: https://pypi.python.org/packages/source/c/cyflann/cyflann-0.1.19.tar.gz
  md5: 1c94e2147f51d9c14ac1fcf5eac5763c

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - flann

  run:
    - python
    - numpy
    - flann

test:
  imports:
    - cyflann

  commands:
    - nosetests --exe cyflann

  requires:
    - nose
    - pyflann

about:
  home: https://github.com/dougalsutherland/cyflann
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
