package:
  name: cyflann
  version: 0.1.24

source:
  fn: cyflann-0.1.24.tar.gz
  url: https://pypi.python.org/packages/a6/0c/6007f6594d28f1d5c963539c0307608fb5443bfff25fcfa44edbf1d8b756/cyflann-0.1.24.tar.gz
  md5: a2f3aff7ae9f9bb24a15287ff8583ce0

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - flann >=1.9.1,<1.10

  run:
    - python
    - numpy x.x
    - flann >=1.9.1,<1.10

test:
  imports:
    - cyflann

  commands:
    - nosetests --exe cyflann

  requires:
    - nose
    - pyflann

about:
  home: https://github.com/dougalsutherland/cyflann
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
