package:
  name: r-r.oo
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.19.0"

source:
  fn: R.oo_1.19.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/R.oo_1.19.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/R.oo/R.oo_1.19.0.tar.gz
  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: tools
requirements:
  build:
    - r >=2.4.0
    - r-r.methodss3 >=1.7.0

  run:
    - r >=2.4.0
    - r-r.methodss3 >=1.7.0

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('R.oo')" # [not win]
    - "\"%R%\" -e \"library('R.oo')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://github.com/HenrikBengtsson/R.oo'

  license: LGPL (>= 2.1)
  summary: !!python/unicode 'Methods and classes for object-oriented programming in R with or
    without references.  Large effort has been made on making definition of methods
    as simple as possible with a minimum of maintenance for package developers.  The
    package has been developed since 2001 and is now considered very stable.  This is
    a cross-platform package implemented in pure R that defines standard S3 classes
    without any tricks.'


# The original CRAN metadata for this package was:

# Package: R.oo
# Version: 1.19.0
# Depends: R (>= 2.4.0), R.methodsS3 (>= 1.7.0)
# Imports: methods, utils
# Suggests: tools
# Date: 2015-02-27
# Title: R Object-Oriented Programming with or without References
# Authors@R: c(person("Henrik", "Bengtsson", role=c("aut", "cre", "cph"), email = "henrikb@braju.com"))
# Author: Henrik Bengtsson [aut, cre, cph]
# Maintainer: Henrik Bengtsson <henrikb@braju.com>
# Description: Methods and classes for object-oriented programming in R with or without references.  Large effort has been made on making definition of methods as simple as possible with a minimum of maintenance for package developers.  The package has been developed since 2001 and is now considered very stable.  This is a cross-platform package implemented in pure R that defines standard S3 classes without any tricks.
# License: LGPL (>= 2.1)
# LazyLoad: TRUE
# URL: https://github.com/HenrikBengtsson/R.oo
# BugReports: https://github.com/HenrikBengtsson/R.oo/issues
# NeedsCompilation: no
# Packaged: 2015-02-27 19:06:32 UTC; hb
# Repository: CRAN
# Date/Publication: 2015-02-28 01:28:49

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml