package:
  name: cvxpy
  version: 0.2.5

source:
  fn: cvxpy-0.2.5.tar.gz
  url: https://pypi.python.org/packages/source/c/cvxpy/cvxpy-0.2.5.tar.gz
  md5: f80b3ed6ca3267ef064134547116d3ab

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - ecos
    - scs
    - cvxopt
    - toolz

  run:
    - python
    - numpy
    - scipy
    - ecos
    - scs
    - cvxopt
    - toolz

test:
  imports:
    - cvxpy
    - cvxpy.atoms
    - cvxpy.atoms.affine
    - cvxpy.atoms.elementwise
    - cvxpy.constraints
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.expressions.variables
    - cvxpy.interface
    - cvxpy.interface.numpy_interface
    - cvxpy.interface.cvxopt_interface
    - cvxpy.lin_ops
    - cvxpy.problems
    - cvxpy.tests
    - cvxpy.utilities

about:
  home: http://github.com/cvxgrp/cvxpy/
  license: GPLv3
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'
