package:
  name: cvxpy
  version: 0.1

source:
  fn: cvxpy-0.1.tar.gz
  url: https://pypi.python.org/packages/source/c/cvxpy/cvxpy-0.1.tar.gz
  md5: c930deac934e4c4b579826bc1f3a8375

requirements:
  build:
    - python
    - numpy
    - scipy
    - ecos
    - cvxopt

  run:
    - python
    - numpy
    - scipy
    - ecos
    - cvxopt

test:
  imports:
    - cvxpy.interface
    - cvxpy.atoms
    - cvxpy.expressions
    - cvxpy.expressions.constants
    - cvxpy.constraints
    - cvxpy.expressions.variables
    - cvxpy.utilities
    - cvxpy
    - cvxpy.tests
    - cvxpy.atoms.elementwise
    - cvxpy.interface.numpy_interface
    - cvxpy.problems
    - cvxpy.interface.cvxopt_interface
    - cvxpy.atoms.affine
    - cvxpy.atoms.nonlinear

about:
  home: http://github.com/cvxgrp/cvxpy/
  license: GPLv3
  summary: 'A domain-specific language for modeling convex optimization problems in Python.'