package:
    name: flann
    version: 1.8.5dev

build:
    number: 8

source:
    git_url: https://github.com/mariusmuja/flann.git
    git_tag: 9a01507d2231b29eb688246a6e442054defa7460

requirements:
    build:
        - cmake
        - hdf5
        - gcc [osx]
    run:
        - hdf5
        - libgcc [osx]

# TODO: build a basic test program

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
