package:
    name: flann
    version: 1.8.5dev

build:
    number: 7

source:
    git_url: git@github.com:mariusmuja/flann.git
    git_tag: 04b4a56533faf8c8228d011d05ba376038364b49

requirements:
    build:
        - cmake
        - hdf5
    run:
        - hdf5

# TODO: build a basic test program

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
