package:
    name: flann
    version: 1.8.5dev

build:
    number: 4

source:
    git_url: git@github.com:mariusmuja/flann.git
    git_tag: 894c1b975e299d15487a6a498862c6b1df39de28

requirements:
    build:
        - cmake
        - python
        - hdf5
    run:
        - python
        - numpy
        - hdf5

test:
  imports:
    - pyflann

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
