package:
    name: flann
    version: 1.9.1

build:
    number: 0

source:
    git_url: https://github.com/mariusmuja/flann.git
    git_tag: 1.9.1

requirements:
    build:
        - cmake
        - hdf5
        - gcc [osx]
    run:
        - hdf5
        - libgcc [osx]

# TODO: build a basic test program

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
