package:
    name: flann
    version: 1.9.1

build:
    number: 1

source:
    url: https://github.com/mariusmuja/flann/archive/1.9.1.tar.gz
    sha256: b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3

requirements:
    build:
        - cmake
        - hdf5
        - gcc [osx]
    run:
        - hdf5
        - libgcc [osx]

# TODO: build a basic test program

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
