package:
    name: flann
    version: 1.8.5dev

source:
    # url: http://people.cs.ubc.ca/~mariusm/uploads/FLANN/flann-1.8.4-src.zip
    # url: https://github.com/mariusmuja/flann/tarball/master
    git_url: git@github.com:mariusmuja/flann.git

requirements:
    build:
        - python
        - hdf5
    run:
        - python
        - numpy
        - hdf5

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
