package:
    name: flann
    version: 1.8.5dev

build:
    number: 3

source:
    git_url: git@github.com:mariusmuja/flann.git

requirements:
    build:
        - python
        - hdf5
    run:
        - python
        - numpy
        - hdf5

test:
  imports:
    - pyflann

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
