package:
    name: flann
    version: 1.8.5dev

build:
    number: 6

source:
    git_url: git@github.com:mariusmuja/flann.git
    git_tag: 894c1b975e299d15487a6a498862c6b1df39de28

requirements:
    build:
        - cmake
        - hdf5
    run:
        - hdf5

# TODO: build a basic test program

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
