package:
    name: flann
    version: 1.8.5dev

build:
    number: 9

source:
    git_url: https://github.com/mariusmuja/flann.git
    git_tag: 31bcbefca205fb9febcaa6823139fd3525f21ed3

requirements:
    build:
        - cmake
        - hdf5
        - gcc [osx]
    run:
        - hdf5
        - libgcc [osx]

# TODO: build a basic test program

about:
    home: https://github.com/mariusmuja/flann
    license: BSD License
